name: Dynamic Version Branch Workflow


on:
  workflow_dispatch:
    inputs:
      snapshot_version:
        description: 'The SNAPSHOT version to set in pom.xml'
        required: true

jobs:
  create_branch_update_version:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout Repository
        uses: actions/checkout@v3

      
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Create New Branch
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git checkout -b dynamic-vars-tasks

      
      - name: Update pom.xml Version
        run: |
          sed -i 's/<version>.*<\/version>/<version>${{ github.event.inputs.snapshot_version }}<\/version>/' pom.xml
          git add pom.xml
          git commit -m "Updated version to ${{ github.event.inputs.snapshot_version }}"

      
      - name: Build with Maven
        run: mvn clean install

      
      - name: Push New Branch
        run: |
          git push origin dynamic-vars-tasks

      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: dynamic-vars-tasks
          title: "Dynamic Variables Task - Version Update"
          body: "This PR updates the version in pom.xml to ${{ github.event.inputs.snapshot_version }}."
          base: main

 
  codeql:
    needs: create_branch_update_version
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
      security-events: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: java

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

 
  merge_pr:
    needs: codeql
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Merge PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Automatically approve and merge the PR
          gh pr merge --squash --admin dynamic-vars-tasks --repo ${{ github.repository }}

