name: Dynamic Version Build

on:
  workflow_dispatch:
    inputs:
      SNAPSHOT_VERSION:
        description: 'Snapshot build version (mandatory)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create dynamic branch
        run: |
          git checkout -b dynamic-vars-tasks

      - name: Update POM.xml with SNAPSHOT version
        run: |
          sed -i "s/<version>.*<\/version>/<version>${{ github.event.inputs.SNAPSHOT_VERSION }}<\/version>/" pom.xml
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add pom.xml
          git commit -m "Update POM.xml to version ${{ github.event.inputs.SNAPSHOT_VERSION }}"

      - name: Build project
        run: mvn clean install

  pr:
    runs-on: ubuntu-latest
    needs: build
    if: success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: 'Dynamic Version Update'
          body: 'This PR updates the POM version to ${{ github.event.inputs.SNAPSHOT_VERSION }}.'
          base: main
          head: dynamic-vars-tasks

      - name: Run CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: 'security'
          output: 'codeql-results.sarif'

  merge:
    runs-on: ubuntu-latest
    needs: pr
    if: success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge Pull Request
        run: |
          git checkout main
          git merge dynamic-vars-tasks
          git push origin main